-- Corrected UCI South German Credit codetable.txt / read_SouthGermanCredit.R.
-- https://archive.ics.uci.edu/static/public/573/south+german+credit+update.zip
-- Codes are category identifiers, not continuous measurements.
INSERT INTO category_lookup (variable_name, category_code, category_label, display_order) VALUES
    ('checking_status', 1, 'no checking account', 1),
    ('checking_status', 2, '... < 0 DM', 2),
    ('checking_status', 3, '0<= ... < 200 DM', 3),
    ('checking_status', 4, '... >= 200 DM / salary for at least 1 year', 4),
    ('credit_history', 0, 'delay in paying off in the past', 1),
    ('credit_history', 1, 'critical account/other credits elsewhere', 2),
    ('credit_history', 2, 'no credits taken/all credits paid back duly', 3),
    ('credit_history', 3, 'existing credits paid back duly till now', 4),
    ('credit_history', 4, 'all credits at this bank paid back duly', 5),
    ('purpose', 0, 'others', 1),
    ('purpose', 1, 'car (new)', 2),
    ('purpose', 2, 'car (used)', 3),
    ('purpose', 3, 'furniture/equipment', 4),
    ('purpose', 4, 'radio/television', 5),
    ('purpose', 5, 'domestic appliances', 6),
    ('purpose', 6, 'repairs', 7),
    ('purpose', 7, 'education', 8),
    ('purpose', 8, 'vacation', 9),
    ('purpose', 9, 'retraining', 10),
    ('purpose', 10, 'business', 11),
    ('savings', 1, 'unknown/no savings account', 1),
    ('savings', 2, '... <  100 DM', 2),
    ('savings', 3, '100 <= ... <  500 DM', 3),
    ('savings', 4, '500 <= ... < 1000 DM', 4),
    ('savings', 5, '... >= 1000 DM', 5),
    ('employment_duration', 1, 'unemployed', 1),
    ('employment_duration', 2, '< 1 yr', 2),
    ('employment_duration', 3, '1 <= ... < 4 yrs', 3),
    ('employment_duration', 4, '4 <= ... < 7 yrs', 4),
    ('employment_duration', 5, '>= 7 yrs', 5),
    ('installment_rate', 1, '>= 35', 1),
    ('installment_rate', 2, '25 <= ... < 35', 2),
    ('installment_rate', 3, '20 <= ... < 25', 3),
    ('installment_rate', 4, '< 20', 4),
    ('personal_status_sex', 1, 'male : divorced/separated', 1),
    ('personal_status_sex', 2, 'female : non-single or male : single', 2),
    ('personal_status_sex', 3, 'male : married/widowed', 3),
    ('personal_status_sex', 4, 'female : single', 4),
    ('other_debtors', 1, 'none', 1),
    ('other_debtors', 2, 'co-applicant', 2),
    ('other_debtors', 3, 'guarantor', 3),
    ('residence_duration', 1, '< 1 yr', 1),
    ('residence_duration', 2, '1 <= ... < 4 yrs', 2),
    ('residence_duration', 3, '4 <= ... < 7 yrs', 3),
    ('residence_duration', 4, '>= 7 yrs', 4),
    ('property', 1, 'unknown / no property', 1),
    ('property', 2, 'car or other', 2),
    ('property', 3, 'building soc. savings agr./life insurance', 3),
    ('property', 4, 'real estate', 4),
    ('other_installment_plans', 1, 'bank', 1),
    ('other_installment_plans', 2, 'stores', 2),
    ('other_installment_plans', 3, 'none', 3),
    ('housing', 1, 'for free', 1),
    ('housing', 2, 'rent', 2),
    ('housing', 3, 'own', 3),
    ('number_credits', 1, '1', 1),
    ('number_credits', 2, '2-3', 2),
    ('number_credits', 3, '4-5', 3),
    ('number_credits', 4, '>= 6', 4),
    ('job', 1, 'unemployed/unskilled - non-resident', 1),
    ('job', 2, 'unskilled - resident', 2),
    ('job', 3, 'skilled employee/official', 3),
    ('job', 4, 'manager/self-empl./highly qualif. employee', 4),
    ('people_liable', 1, '3 or more', 1),
    ('people_liable', 2, '0 to 2', 2),
    ('telephone', 1, 'no', 1),
    ('telephone', 2, 'yes (under customer name)', 2),
    ('foreign_worker', 1, 'yes', 1),
    ('foreign_worker', 2, 'no', 2);
